project:
  type: website
  output-dir: docs

website:
  title: "joeroith.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - courses.qmd
      - 02_maps.qmd
      - 14b_first_Shiny_flexdash.Rmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

